spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gymposesdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 6D5A7134743777217A25432A462D4A614E645267556B58703273357638792F42
  expiration: 86400000
